name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.9.36+4
homepage: https://github.com/cloudwebrtc/flutter-webrtc
publish_to: none
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  collection: ^1.17.1
  dart_webrtc:
    git:
        url: https://github.com/lambiengcode/dart-webrtc.git
        path: "."
        ref: 1.1.1+1
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  webrtc_interface:
    git:
      url: https://github.com/lambiengcode/webrtc-interface.git
      path: "."
      ref: 1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
